### ISSUE TITLE
List Index out of bounds

### ISSUE THREAD

**Issue by Akshay-shiva** [abhinavsood/mutual-fund-analysis#2]
table = soup.find_all('table', attrs = {"class": "tblfund1"})[0]
(line 70 ) throws this error
> Traceback (most recent call last):
  File "/home/shivakrishna/mutual fund/moneycontrol.py", line 70, in <module>
    table = soup.find_all('table', attrs = {"class": "tblfund1"})[0]
IndexError: list index out of range

**Comment by abhinavsood** [comment]
If you follow the link that the script is trying to [get the data from](https://github.com/abhinavsood/mutual-fund-analysis/blob/master/00_moneycontrol.py#L61-L64) in a browser, you'll realize that both the page URL as well as the page structure have changed.

A quick look tells me that that the new URL is `https://www.moneycontrol.com/mutualfundindia/` and the new table in found in `#tbequity .mctable1`. There could potentially be more changes to the underlying structure. I haven't updated the script in years  and do not have time or motivation to do so currently, but you're welcome to send a Pull Request if you do decide to update it.
